apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      type: backend-dep
  template:
    metadata:
      labels:
        type: backend-dep
    spec:
      containers:
        - name: my-container
          image: subhanali/microservices:v2
          ports:
            - containerPort: 5000