apiVersion: apps/v1
kind: Deployment
metadata:
  name: fst-deployment-services
spec:
  replicas: 4
  selector:
    matchLabels:
      type: test-app
  template:
    metadata:
      labels:
        type: test-app
    spec:
      containers:
        - name: my-container
          image: subhanali/microservices
          ports:
            - containerPort: 5000