apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      type: mongod
  template:
    metadata:
      labels:
        type: mongod
    spec:
      containers:
        - name: db-container
          image: mongo
          ports:
            - containerPort: 27017
